### ISSUE TITLE
Croppa with angularjs

### ISSUE THREAD

**Issue by sergeh** [BKWLD/croppa#105]
This might be out of scope but I was wondering if there was a way to use croppa in angularjs (using ng-repeat).

I've been using a modified version of [angular-croppa](https://github.com/atwright147/angular-croppa) but after I transferred everything to a new server, all images were returning 404s. The issue was fixed by setting `signing_key` to `false`

**Comment by weotch** [comment]
Yeah, that issue you're talking about was because of the feature I added in [4.2.0](https://github.com/BKWLD/croppa/releases/tag/4.2.0).  Disabling it is perfectly valid, though.

What I generally do is make an accessor on my models that creates the URL and serves to JS via some AJAX API.  So PHP is still creating the signed Croppa URLs.
