### ISSUE TITLE
Integration with S3 and CloudFornt

### ISSUE THREAD

**Issue by vics80** [BKWLD/croppa#107]
Hi,

I'm developing a web with a lot of images. Then I create an AWS account to test S3 and CloudFront to put all the images.

I woud like to use Croppa but I don't know how can I integrate with S3/CloudFront.

I haven't a domain yet. I'm developing in my local computer. Then the URLs are with CloudFront path.

Can you help me?

**Comment by weotch** [comment]
If you want the crops to get created on S3, you'll need to do something like https://github.com/BKWLD/croppa#src-images-on-s3-local-crops but use `s3` for your `crops_dir` as well.  Note, there is a performance hit for this because your web app will be checking to see if a crop exists on every image request.  

Croppa may not be the best fit for this, it's best suited to storing the crops on your web server.
