### ISSUE TITLE
Create API for generating an image using Croppa::url method signature

### ISSUE THREAD

**Issue by repkins** [BKWLD/croppa#111]
Hello! 

At first, I want to say thanks to author for amazing library, I really like it. I like an idea, when it generates image thumbnails based on URL when they are not exists in server. 

I wondering, if there can be the way to generate non-existent thumbnails on URLs creation. Because it makes more perfomance boost for all request lifecycle from a browser for end user, preparing thumnail images while creating HTML, which at last anyway will be rendered in a browser, rather than first making URLs and them generating thumbnails while browser rendering page, making sequental thumbnail requests to server to get such images, which of course at first will be generated though PHP, slowing down image getting response time.

I hope you got my point. I'm not a native English speaker, so I'm sorry about possible mistakes.

Best regards, repkins!

**Comment by weotch** [comment]
I don't think I'd want `Croppa::url()` to actually generate the image.  That would mean that if a public page had 20 images on it, it would super slow rendering that page because the image generation would block the html response.  Whereas, with the current way Croppa works, the images are generated in separate apache processes, they don't block the HTML from returning.

Instead, I think the way to implement this feature would be a new API that would let you create the image directly.  Like `Croppa::render()` or something.

**Comment by repkins** [comment]
That's a point about blocking HTML response.

Then, ok, would be great to let generate images direcly, and more better it returns ready URL path just like `Croppa::url()` does. It also will be useful for preloading images in another process like cron, etc.

**Comment by weotch** [comment]
@dannoso did this work and is currently merged into master branch.  🎉

**Comment by repkins** [comment]
Great! Thanks, @dannoso!
