### ISSUE TITLE
Lumen - Route Regex formatting issue?

### ISSUE THREAD

**Issue by ryanscherler** [BKWLD/croppa#130]
Hey BKWLD team,

I've used Croppa on a full Laravel site, and am now attempting to add a bit of image manipulation to a micro service in Lumen. I've added all the necessary installation steps for Lumen, but when I try and boot the app I am getting this error:

```
BadRouteException in RegexBasedAbstract.php line 108:
Regex "(?=images/(?:crops/)?(.*)$)(?=(.+)-([0-9_]+)x([0-9_]+)(-[0-9a-zA-Z(),\-._]+)*\.(jpg|jpeg|png|gif|JPG|JPEG|PNG|GIF)$).+" for parameter "path" contains a capturing group
```

Here is my config file in /config/croppa.php 

```
<?php return [
	'src_dir'    => public_path('images'),
	'crops_dir'  => public_path('images/crops'),
	'path'       => 'images/(?:crops/)?(.*)$',
	'url_prefix' => '/images/crops/',
];
```

It seems that maybe this regex is not fully supported by FastRoute (the routing used by Lumen vs. the full router in Laravel? Do you have suggestions on how to reformat this regex to work with the latest Lumen version?

Thanks in advance!

**Comment by ryanscherler** [comment]
After playing with this a bit more, I think maybe the regex issue is the appended rules to the path (in the core Croppa method). Have you used Croppa on Lumen recently to verify this possible bug?

**Comment by weotch** [comment]
I haven't used it on Lumen recently, no.  That's disappointing to hear, that regex, as you can tell, is pretty intense and not the easiest to mess around with. 

I saw this in the FastRoute readme:

> Custom patterns for route placeholders cannot use capturing groups. For example {lang:(en|de)} is not a valid placeholder, because () is a capturing group. Instead you can use either {lang:en|de} or {lang:(?:en|de)}

[When I add the route handler](https://github.com/BKWLD/croppa/blob/master/src/Bkwld/Croppa/ServiceProvider.php#L100-L102), I am passing the whole regex to a route placeholder.  And it contains capturing groups.

I think a fix for this, if you wanna fork it and work on it, would be to change both the Laravel and Lumen route handlers from using route placeholder variables at all to just validating the route using  the `routePattern()`.  Then, in `Bkwld\Croppa\Handler@handle`, re-parse out the `$path` from the request URL, instead of receiving it as a parameter in the call from the route handler.

**Comment by ryanscherler** [comment]
Hi Robert,

Thanks for the info on this - I kinda figured it was due to that complex regex being passed into the route placeholder. I'll take a look and see about retrofitting that to parse the path from the request URL as you referred to in the handle method.

Also - I realized that we've met! Its been a long time - I came up and visited you in the BKWLD office some time ago. I was at an agency downtown and looking to see about options with joining the BKWLD team. Excited to see you guys doing so well! 

Would love to catch up sometime and hear about what you and the team are up to now. Its great to hear you're using Laravel for a lot of projects - really great framework.

Talk soon!

– Ryan

Designer / Developer
East Slope Studio LLC
ph: 360.393.9756
ryan@eastslopestudio.com
eastslopestudio.com

**Comment by weotch** [comment]
Oh yeahhh haha, hey dude!  Funny!  

Yeah, we leaned into Laravel pretty heavily.  We've followed that community into Vue.js and Webpack too, for frontend stuff.

**Comment by ryanscherler** [comment]
Nice! its quickly becoming our stack as well. We're working on a project right now using Laravel, Vue etc. - really nice setup and such a simpler approach than React / JSX which looks quite frankly gross to build with. 

Lets keep in touch! (I am going to close out this issue as well and we can resume outside Github haha)

Talk soon,

**Comment by Gevie** [comment]
This still appears to be an issue with Lumen's FastRoute. I have a temporary fix, I haven't forked because it isn't a good fix and should be done properly.

In ServiceProvider::boot, line 100 change `$this->app->get('{path:'.$this->app['Bkwld\Croppa\URL']->routePattern().'}', [` to `$this->app->get('images/posts/{image}', [` replacing images/posts with your appropriate path from config.

In URL::relativePath() after `$path = $this->toPath($url);` line 159 add `return $path`

This should get Croppa working via the URL, I've not experimented much but it appears to work fine, again I don't advise doing this - this is a temporary fix just as a matter of urgency in my case.

**Comment by dangerousdan** [comment]
This is because FastRoute is throwing the error

    Regex "%s" for parameter "%s" contains a capturing group

We just need to change the capturing groups to non-capturing groups by adding `?:`

    const PATTERN = '(?:.+)-(?:[0-9_]+)x(?:[0-9_]+)(?:-[0-9a-zA-Z(),\-._]+)*\.(?:jpg|jpeg|png|gif|JPG|JPEG|PNG|GIF)$';

as well as adding `?:` to any regex capturing groups in your config.

**Comment by dangerousdan** [comment]
Ignore the suggestion above - that fixes the Lumen routing, but causes issues elsewhere.

The correct solution seems to be to name the regex capture-groups, which [FastRoute allows](
https://github.com/nikic/FastRoute/blob/master/src/DataGenerator/RegexBasedAbstract.php#L137)

See the PR above.

**Comment by weotch** [comment]
@dangerousdan's PR is mergred into master now

**Comment by vitalijalbu** [comment]
Hi guys, I also want to include file with extension in lumen route, how can i?
