### ISSUE TITLE
When a source image doesn't exists, it would be better for the controller to answer with a 404 code

### ISSUE THREAD

**Issue by xel1045** [BKWLD/croppa#69]
Actually, when a crawler try to fetch an old image, its get a 500 application error

**Comment by weotch** [comment]
You're talking about the `Croppa: Referenced file missing` exception right? 

I'm torn on this.  IMO, if the source image doesn't exist, there is a problem with the app code and the developer should be notified of that problem via general exception reporting tools.

However, in practice, when I get notifications of that sort, I usually don't investigate because most of the time it's a race condition and isn't an issue on subsequent requests.  So the exception notifications just become noise.

**Comment by xel1045** [comment]
Yes I'm talking about the `Croppa: Referenced file missing` exception.

Since croppa is adding a catch-all route, this exception is thrown even for images that are not in the defined source paths. We migrated a website that had pictures matching the `pattern` regex but are not part of the new website's content. Google has indexed theses pictures years before and keeps trying to fetch them even if they not exist anymore. Those images are not displayed on rendered pages because we're not informing them they're not available anymore (with a 404).

Here's a small example of the path to an image on the old website: `/content/products/d/db/cadre-az-soho-5x7-8x10-noir.jpg`

In terms of HTTP status, I think a 404 status code is more logical than a 500 (Internal Server Error). I understand that it records missing source files, but these can be found by looking at the access_log. If you want to be sure those errors are not ignored, you could use the Log::warning to add this to laravel's log file.

**Comment by weotch** [comment]
Yeah, I agree with you.  I think your example of dead links that some other app (Google for example) maintains after you've deleted images is the source of a lot of the errors I've seen.

I'll make this change.

**Comment by xel1045** [comment]
Cool! Thanks! ;)
