### ISSUE TITLE
Use croppa with files in Storage

### ISSUE THREAD

**Issue by dusandevic** [BKWLD/croppa#91]
My files are located in project/storage/app/* folder.

This is how I retrieve files from the controller: 

```
$file = Storage::disk('local')->get($entry->filename);
		return (new Response($file, 200))
              ->header('Content-Type', $entry->mime);	
```

How can I use this awesome library with such use case?

**Comment by weotch** [comment]
This looks to me like you have a controller action that is outputting images.  This isn't really what Croppa is designed for, you'd use Croppa **instead** of writing a controller action like this.  And you'd do that so that subsequent requests for the route to your crop get served by Apache, saving your server the overhead of booting up PHP.

For what you're doing there, look at [Intervention and it's caching feature](http://image.intervention.io/use/cache)

**Comment by weotch** [comment]
Let me also add, if you WANT to use croppa, I think your config with that setup would be like:

```php
<?php return [
  'src_dir' => storage_path(),
  'crops_dir' => public_path().'/uploads',
  'path' => 'uploads/(.*)$',
];

**Comment by weotch** [comment]
I've added some examples here: https://github.com/BKWLD/croppa/wiki/Examples
