### ISSUE TITLE
Still does not delete crops.

### ISSUE THREAD

**Issue by d-lamers** [BKWLD/croppa#97]
I have the config as default. The version set to dev-master.

But it does not delete the crops. (See images)

Before
![schermafbeelding 2015-06-23 om 09 06 46](https://cloud.githubusercontent.com/assets/3164508/8300673/744a6d24-1987-11e5-9831-c8e12f719bac.png)

After delete
![schermafbeelding 2015-06-23 om 09 07 08](https://cloud.githubusercontent.com/assets/3164508/8300672/74486ed4-1987-11e5-8f3c-60e1af04817e.png)

**Comment by weotch** [comment]
Ok, try that out.  I was able to reproduce your issue outside of unit tests and https://github.com/BKWLD/croppa/commit/64360952813c0147128e1937d429423849b7d10f fixed it for me.  It was something my tests weren't covering because I was passing the wrong path to Flysystem's `listContents()`, which is totally stubbed out in my tests.

**Comment by d-lamers** [comment]
I'm afraid I can't test it because im going on vacation for 7 weeks. But wanted to say thx for your work! And I will be testing this as soon as im back.

**Comment by weotch** [comment]
Well damn, enjoy that!

**Comment by weotch** [comment]
Btw, I released the above commits in [4.0.5](Sure thing, released here: https://github.com/BKWLD/croppa/releases/tag/4.0.5)
